# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20171030_1934'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sessions',
            unique_together=set([('studentID', 'tutorID', 'bookedTime')]),
        ),
    ]
