# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20171030_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='end_time',
            new_name='endTime',
        ),
        migrations.RenameField(
            model_name='availability',
            old_name='start_time',
            new_name='startTime',
        ),
        migrations.AddField(
            model_name='availability',
            name='isAvailable',
            field=models.BooleanField(default=True),
        ),
    ]
