# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20171030_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='isAvailable',
        ),
    ]
