# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_availability_isavailable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='bookedTime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookedTime', to='main.Availability'),
        ),
    ]
