# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20171030_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='bookedTime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessionKey', to='main.Availability'),
        ),
    ]
