# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20171030_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='tutorType',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Contracted'), (1, 'Private')], default=0),
        ),
    ]
