# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_tutor_tutortype'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
