# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 02:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20171031_1042'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sessions',
            unique_together=set([('studentID', 'bookedTime'), ('studentID', 'tutorID', 'bookedTime')]),
        ),
    ]
