# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_remove_tutor_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='courses',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Courses'),
            preserve_default=False,
        ),
    ]
