# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_availability_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='day',
            field=models.PositiveSmallIntegerField(choices=[(0, '1'), (1, '2'), (2, '3'), (3, '4'), (4, '5'), (5, '6'), (6, '7'), (7, '8'), (8, '9'), (9, '10'), (10, '11'), (11, '12'), (12, '13'), (13, '14'), (14, '15'), (15, '16'), (16, '17'), (17, '18'), (18, '19'), (19, '20'), (20, '21'), (21, '22'), (22, '23'), (23, '24'), (24, '25'), (25, '26'), (26, '27'), (27, '28'), (28, '29'), (29, '30'), (30, '31'), (31, '32')], default=0),
            preserve_default=False,
        ),
    ]
