# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_availability_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=8),
        ),
    ]
