# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-11 10:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0044_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='tutor_email',
        ),
        migrations.AddField(
            model_name='tutor',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
