# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-11 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_remove_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='x@y.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
