# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-11 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='tutor_email',
            field=models.EmailField(default='x@z.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
