# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_auto_20171113_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='date',
            field=models.DateField(),
        ),
    ]
