# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_auto_20171113_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='sessionAmount',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=8),
            preserve_default=False,
        ),
    ]
