# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_coupon_review_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systemBalance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sessionDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Sessions')),
            ],
        ),
    ]
