# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_systemwallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemwallet',
            name='sessionDetails',
        ),
        migrations.AddField(
            model_name='sessions',
            name='systemWallet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.SystemWallet'),
            preserve_default=False,
        ),
    ]
