# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_remove_systemwallet_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='isStudent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=8),
        ),
    ]
