# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-18 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_auto_20171117_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='bookedDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessions',
            name='bookedEndTime',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessions',
            name='bookedStartTime',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='sessions',
            name='bookedTime',
        ),
        migrations.AlterUniqueTogether(
            name='sessions',
            unique_together=set([('studentID', 'tutorID', 'bookedDate', 'bookedStartTime', 'bookedEndTime')]),
        ),
    ]
