# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('main', '0066_remove_availability_isavailable'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemwallet',
            name='site',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together=set([('tutor', 'date', 'startTime', 'endTime')]),
        ),
    ]
