# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_auto_20171120_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='tutor_booking_status',
        ),
    ]
