# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_remove_tutor_tutor_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='wallet',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
