# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_transactions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='transactionAmount',
            new_name='addedAmount',
        ),
        migrations.AddField(
            model_name='transactions',
            name='subtractedAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
