# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_auto_20171121_0037'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sessions',
            unique_together=set([('studentID', 'tutorID', 'bookedDate', 'bookedStartTime', 'bookedEndTime'), ('studentID', 'tutorID', 'bookedDate')]),
        ),
    ]
