# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_auto_20171121_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
