# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0078_review_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comments',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=6, null=True),
        ),
    ]
