# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_auto_20171121_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessions',
            name='systemWallet',
        ),
    ]
