# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0080_remove_sessions_systemwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
