# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_review_reviewtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='reviewTime',
        ),
        migrations.RemoveField(
            model_name='review',
            name='student',
        ),
        migrations.RemoveField(
            model_name='review',
            name='tutor',
        ),
        migrations.AddField(
            model_name='review',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Sessions'),
        ),
    ]
