# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0083_auto_20171122_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='isAnonymous',
            field=models.BooleanField(default=False),
        ),
    ]
