# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_review_isanonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
