# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0085_tutor_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='avatar',
            field=models.ImageField(upload_to='profile_pics'),
        ),
    ]
