# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0088_student_phoneno'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='averageRating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
