# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0090_tutor_numreviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='searchTags',
        ),
        migrations.AddField(
            model_name='tutor',
            name='searchTags',
            field=models.CharField(default='Java', max_length=256),
        ),
    ]
