# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0091_auto_20171123_0708'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchTag',
        ),
        migrations.AddField(
            model_name='student',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
