# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 13:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0093_auto_20171123_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='phoneNo',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999999), django.core.validators.MinValueValidator(11111111)]),
        ),
    ]
